

[[news]]
date = "2023-09"
content = "Starting my PhD at Southeast University"

date = "2025-09"
content = "MoE-Gyro has been accepted to the NeurIPS 2025 main conference"

date = "2026-02"
content = "RL-VIO has been accepted to the CVPR 2026 main conference"
